### ISSUE TITLE
Doesn't lint some css files

### ISSUE THREAD

**Issue by ismay** [1000ch/linter-stylelint#2]
Not sure why, but linter-stylelint doesn't lint all css files. For example, it lints this file:

```css
/**
 * CourseMaterialItem
 * =============================================================================
 */

/**
 * Main component class
 */

.CourseMaterialItem {
  margin-bottom: 0.5rem;
}

.CourseMaterialItem-link {
  border-radius: var(--border-radius);
  border: 2px solid var(--gray-light);
  color: var(--gray-dark);
  display: block;
  font-weight: 600;
  padding: 0.75rem 1rem;
  text-transform: capitalize;
  transition: var(--transition);
}

.CourseMaterialItem-link:--interaction {
  background: var(--gray);
  border-color: var(--gray);
  color: var(--white);
}

```

But it doesn't lint this file:

```css
/**
 * Grid
 * =============================================================================
 * A CSS flexbox grid component, based on Philip Waltons Solved by Flexbox grid:
 * philipwalton.github.io/solved-by-flexbox/demos/grids/
 *
 * Meant to be used with the 'size' responsive sizing utilities.
 *
 * TODO Add offset classes, order reversing, horizontal space division.
 */

@import '../base/breakpoints';

 /**
  * Settings
  */
:root {
  --Grid-gutterSm: 1.0rem;
  --Grid-gutterMd: 1.5rem;
  --Grid-gutterLg: 2.0rem;
}

/**
 * Main component class
 *
 * 1. Cells distribute horizontal space evenly by default.
 */
.Grid {
  display: flex;
  flex-wrap: wrap;
  list-style: none;
  margin: 0;
  padding: 0;
}

.Grid-cell {
  flex: 1; /* 1 */
}

/**
 * Modifiers: vertical cell alignment
 */
.Grid--top {
  align-items: flex-start;
}

.Grid--bottom {
  align-items: flex-end;
}

.Grid--center {
  align-items: center;
}

/**
 * Modifiers: vertical cell self-alignment
 */
.Grid-cell--top {
  align-self: flex-start;
}

.Grid-cell--bottom {
  align-self: flex-end;
}

.Grid-cell--center {
  align-self: center;
}

/**
 * Modifier: center cells horizontally
 */
.Grid--justifyCenter {
  justify-content: center;
}

/**
 * Modifiers: change cell order
 */
.sm-Grid-cell--first {
  order: -1;
}

.sm-Grid-cell--last {
  order: 1000;
}

/**
 * Responsive cell order modifiers
 */
@media (--md-up) {
  .md-Grid-cell--first {
    order: -1;
  }

  .md-Grid-cell--last {
    order: 1000;
  }
}

/**
 * Modifiers: set all cell widths
 *
 * 1. Distribute width evenly between cells (default)
 * 2. All cells 100% width
 * 3. Shrinkwrap all cells
 */
.sm-Grid--fit > .Grid-cell { /* 1 */
  flex: 1;
}

.sm-Grid--full > .Grid-cell { /* 2 */
  flex: 0 0 100%;
}

.sm-Grid--shrink > .Grid-cell { /* 3 */
  flex: 0 1 0;
}

.sm-Grid--1of2 > .Grid-cell {
  flex: 0 0 50%;
}

.sm-Grid--1of3 > .Grid-cell {
  flex: 0 0 33.3333%;
}

.sm-Grid--1of4 > .Grid-cell {
  flex: 0 0 25%;
}

/**
 * Responsive cell width modifiers
 */
@media (--md-up) {
  .md-Grid--fit > .Grid-cell {
    flex: 1;
  }

  .md-Grid--full > .Grid-cell {
    flex: 0 0 100%;
  }

  .md-Grid--1of2 > .Grid-cell {
    flex: 0 0 50%;
  }

  .md-Grid--1of3 > .Grid-cell {
    flex: 0 0 33.3333%;
  }

  .md-Grid--1of4 > .Grid-cell {
    flex: 0 0 25%;
  }
}

@media (--lg-up) {
  .lg-Grid--fit > .Grid-cell {
    flex: 1;
  }

  .lg-Grid--full > .Grid-cell {
    flex: 0 0 100%;
  }

  .lg-Grid--1of2 > .Grid-cell {
    flex: 0 0 50%;
  }

  .lg-Grid--1of3 > .Grid-cell {
    flex: 0 0 33.3333%;
  }

  .lg-Grid--1of4 > .Grid-cell {
    flex: 0 0 25%;
  }
}

/**
 * Modifier: gutters between grid cells
 *
 * [screen size]-Grid--gutters[gutter size]
 *
 * Because of our mobile first approach, the classes prefixed with sm-* apply to
 * all screen sizes, unless overwritten. Gutters can be either small, medium or
 * large. Which is indicated by the {Sm,Md,Lg} suffix.
 */
.sm-Grid--guttersSm {
  margin-top: calc(-1 * var(--Grid-gutterSm));
  margin-right: 0;
  margin-bottom: var(--Grid-gutterSm);
  margin-left: calc(-1 * var(--Grid-gutterSm));
}

.sm-Grid--guttersSm > .Grid-cell {
  padding-top: var(--Grid-gutterSm);
  padding-right: 0;
  padding-bottom: 0;
  padding-left: var(--Grid-gutterSm);
}

.sm-Grid--guttersMd {
  margin-top: calc(-1 * var(--Grid-gutterMd));
  margin-right: 0;
  margin-bottom: var(--Grid-gutterMd);
  margin-left: calc(-1 * var(--Grid-gutterMd));
}
.sm-Grid--guttersMd > .Grid-cell {
  padding-top: var(--Grid-gutterMd);
  padding-right: 0;
  padding-bottom: 0;
  padding-left: var(--Grid-gutterMd);
}

.sm-Grid--guttersLg {
  margin-top: calc(-1 * var(--Grid-gutterLg));
  margin-right: 0;
  margin-bottom: var(--Grid-gutterLg);
  margin-left: calc(-1 * var(--Grid-gutterLg));
}

.sm-Grid--guttersLg > .Grid-cell {
  padding-top: var(--Grid-gutterLg);
  padding-right: 0;
  padding-bottom: 0;
  padding-left: var(--Grid-gutterLg);
}

/**
 * Responsive gutter modifiers
 */
@media (--md-up) {
  .md-Grid--guttersSm {
    margin-top: calc(-1 * var(--Grid-gutterSm));
    margin-right: 0;
    margin-bottom: var(--Grid-gutterSm);
    margin-left: calc(-1 * var(--Grid-gutterSm));
  }

  .md-Grid--guttersSm > .Grid-cell {
    padding-top: var(--Grid-gutterSm);
    padding-right: 0;
    padding-bottom: 0;
    padding-left: var(--Grid-gutterSm);
  }

  .md-Grid--guttersMd {
    margin-top: calc(-1 * var(--Grid-gutterMd));
    margin-right: 0;
    margin-bottom: var(--Grid-gutterMd);
    margin-left: calc(-1 * var(--Grid-gutterMd));
  }

  .md-Grid--guttersMd > .Grid-cell {
    padding-top: var(--Grid-gutterMd);
    padding-right: 0;
    padding-bottom: 0;
    padding-left: var(--Grid-gutterMd);
  }

  .md-Grid--guttersLg {
    margin-top: calc(-1 * var(--Grid-gutterLg));
    margin-right: 0;
    margin-bottom: var(--Grid-gutterLg);
    margin-left: calc(-1 * var(--Grid-gutterLg));
  }

  .md-Grid--guttersLg > .Grid-cell {
    padding-top: var(--Grid-gutterLg);
    padding-right: 0;
    padding-bottom: 0;
    padding-left: var(--Grid-gutterLg);
  }
}

@media (--lg-up) {
  .lg-Grid--guttersSm {
    margin-top: calc(-1 * var(--Grid-gutterSm));
    margin-right: 0;
    margin-bottom: var(--Grid-gutterSm);
    margin-left: calc(-1 * var(--Grid-gutterSm));
  }

  .lg-Grid--guttersSm > .Grid-cell {
    padding-top: var(--Grid-gutterSm);
    padding-right: 0;
    padding-bottom: 0;
    padding-left: var(--Grid-gutterSm);
  }

  .lg-Grid--guttersMd {
    margin-top: calc(-1 * var(--Grid-gutterMd));
    margin-right: 0;
    margin-bottom: var(--Grid-gutterMd);
    margin-left: calc(-1 * var(--Grid-gutterMd));
  }

  .lg-Grid--guttersMd > .Grid-cell {
    padding-top: var(--Grid-gutterMd);
    padding-right: 0;
    padding-bottom: 0;
    padding-left: var(--Grid-gutterMd);
  }

  .lg-Grid--guttersLg {
    margin-top: calc(-1 * var(--Grid-gutterLg));
    margin-right: 0;
    margin-bottom: var(--Grid-gutterLg);
    margin-left: calc(-1 * var(--Grid-gutterLg));
  }

  .lg-Grid--guttersLg > .Grid-cell {
    padding-top: var(--Grid-gutterLg);
    padding-right: 0;
    padding-bottom: 0;
    padding-left: var(--Grid-gutterLg);
  }
}

```
